# NOTE: ChangeLog自動生成に関する詳細情報をまとめています↓
# @see https://docs.google.com/document/d/1vRLu7KIPOgotDpa7aiEILq3buKmfvBnU1HpAQaam8cY/edit#
name: Merge production to main

on:
  push:
    branches:
      - "production"
  workflow_dispatch:

env:
  user_name: ${{ vars.GIT_USER_NAME }}
  user_email: ${{ vars.GIT_USER_EMAIL }}

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: production
          fetch-depth: 0
      - name: Git commit
        run: |
          git config user.name $user_name
          git config user.email $user_email

          git fetch
          git switch main

          set +e
          git diff main..production -- public/changelog.json –exit-code
          exists_diff=$?
          set -e

          if [ $exists_diff -eq 0 ]; then
            git merge production
            git push origin main
          else
            echo "差分はありません"
          fi
      - name: Notify slack
        uses: rtCamp/action-slack-notify@v2.0.2
        if: failure()
        env:
          SLACK_CHANNEL: pj-mieruka-pulse
          SLACK_TITLE: "[Ogawa Finder] mainブランチへのmergeに失敗しました"
          SLACK_MESSAGE: コンフリクトしている場合、手動操作にて、コンフリクト解消・mainブランチへのpushを実施してください
          SLACK_COLOR: "#EDB22F"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
