# NOTE: ChangeLog自動生成に関する詳細情報をまとめています↓
# @see https://docs.google.com/document/d/1vRLu7KIPOgotDpa7aiEILq3buKmfvBnU1HpAQaam8cY/edit#
name: Generate Change Log for production

on:
  pull_request:
    types: [opened]
    branches:
      - "production"
  workflow_dispatch:

env:
  user_name: ${{ vars.GIT_USER_NAME }}
  user_email: ${{ vars.GIT_USER_EMAIL }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - name: Print Payload
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: staging
          fetch-depth: 0
      - name: Git tag
        run: |
          # 古いgit tagを削除
          scripts/changelog/delete-old-tag.sh

          # 最新コミットにバージョンタグを付与
          scripts/changelog/add-version-tag.sh
      - name: Generate
        id: generate
        uses: ./.github/actions/generate
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branch: staging
      - name: Post Generate file
        run: |
          pull_requests_count=$(echo ${{ steps.generate.outputs.changelog }} | jq '.[0].pull_requests | length')

          if [ "$pull_requests_count" -eq 0 ]; then
            echo "pull_requestsの要素数は0件のため、自動生成をスキップします"
            exit 0
          fi

          # Changelog生成のための一時ファイル(gitignore)
          mkdir -p temp/generate

          base_path="temp/generate"
          file_name="latest_changelog.json"

          echo ${{ steps.generate.outputs.changelog }} > ${base_path}/${file_name}
          scripts/changelog/add-to-public.sh $base_path $file_name
      - name: Git commit
        run: |
          git config user.name $user_name
          git config user.email $user_email
          git add .
          git commit -m "chore: generate changelog for production"
          git push origin staging
