name: Generate Change Log for production

on:
  pull_request:
    types: [opened]
    branches:
      - "prd"
  workflow_dispatch:

env:
  user_name: ${{ vars.GIT_USER_NAME }}
  user_email: ${{ vars.GIT_USER_EMAIL }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - name: Print Payload
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: stg
          fetch-depth: 0
      - name: Git tag
        run: |
          # 古いgit tagを削除
          scripts/changelog/delete-old-tag.sh

          # 最新コミットにバージョンタグを付与
          scripts/changelog/git-tag-latest-version.sh
      - name: Generate
        id: generate
        uses: ./.github/actions/generate
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branch: stg
      - name: Post Generate file
        run: scripts/changelog/post-generate-file.sh ${{ steps.generate.outputs.changelog }}
      - name: Git commit
        run: |
          git config user.name $user_name
          git config user.email $user_email
          git add .
          git commit -m "chore: generate changelog for production"
          git push origin stg
