name: Generate Change Log

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "stg"
  workflow_dispatch:

env:
  user_name: ${{ vars.GIT_USER_NAME }}
  user_email: ${{ vars.GIT_USER_EMAIL }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - name: Print Payload
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Get Package
        run: go install github.com/Songmu/ghch/cmd/ghch@latest
      - name: Git tag
        run: |
          git config user.name $user_name
          git config user.email $user_email

          tag_stg=stg.latest
          git tag | grep $tag_stg

          # stg.tempタグが存在する場合、最新コミットにタグを付け替え
          if [ $? = 0 ]; then
            commit_log=$(git show $tag_stg | grep commit) # commit afea0fcbd41559c0326998a5ff93b46a74d982f6
            commit_hash=${commit_log#commit } # afea0fcbd41559c0326998a5ff93b46a74d982f6
            tag_target=$(git tag -l --contains $commit_hash | grep -v $tag_stg) # 20230215.1

            git tag -d $tag_target
            git push origin --delete $tag_target

            git tag -d $tag_stg
            git push origin --delete $tag_stg
          fi

          git tag $tag_stg
          git push origin $tag_stg

          yyyymmddhhmm=$(date "+%Y%m%d.%H.%M")
          git tag $yyyymmddhhmm
          git push origin $yyyymmddhhmm
      - name: Generate
        run: |
          generated=$(ghch --latest)
          filtered=$(echo $generated | jq '. | { changed_at: .changed_at, from_revision: .from_revision, to_revision: .to_revision, pull_requests: .pull_requests | map({title: .title}) }')
          filter_untagged=$(echo $filtered | jq '. | select(.to_revision != "")')
          filter_empty=$(echo $filter_untagged | jq '. | select(.pull_requests | length != 0)')
          filter_type=$(echo $filter_empty | jq 'del(. | .pull_requests[] | select(.title | test("(feat|fix)") | not))')
          result=$(echo $filter_type | jq -s .)

          echo $result > latest_changelog.json
          jq -s '.[0] + .[1]' latest_changelog.json changelog.json > pre_generated.json
          mv pre_generated.json changelog.json
      # TODO: git user
      - name: Git commit
        run: |
          git config user.name $user_name
          git config user.email $user_email
          git add .
          git commit -m "chore: generate changelog"
          git push origin main
      - name: Save Changelog
        uses: actions/upload-artifact@v2
        with:
          name: changelog
          path: ./
