name: Generate Change Log

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - "stg"
  workflow_dispatch:

env:
  user_name: ${{ vars.GIT_USER_NAME }}
  user_email: ${{ vars.GIT_USER_EMAIL }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - name: Print Payload
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Get Package
        run: go install github.com/Songmu/ghch/cmd/ghch@latest
      - name: Git tag
        run: |
          git config user.name $user_name
          git config user.email $user_email

          tag_stg=stg.latest

          set +e
          git tag | grep $tag_stg
          # 既存のstg.latestタグを削除
          if [ $? = 0 ]; then
            commit_log=$(git show $tag_stg | grep commit)
            commit_hash=${commit_log#commit }
            tag_version=$(git tag -l --contains $commit_hash | grep -v $tag_stg)

            # stg.latestタグをセットになっているバージョンタグ削除
            git tag -d $tag_version
            git push origin --delete $tag_version

            # stg.latestタグ削除
            git tag -d $tag_stg
            git push origin --delete $tag_stg
          fi
          set -e

          # 最新コミットにstg.latestタグを付与
          git tag $tag_stg
          git push origin $tag_stg

          # 最新コミットにバージョンタグを付与
          tag_version=$(date "+%Y%m%d.%H.%M")
          git tag $tag_version
          git push origin $tag_version
      - name: Generate
        run: |
          # Changelog生成のための一時ファイル(gitignore)
          mkdir generate

          # 最新のchangelogを生成
          generated=$(ghch --latest)
          filtered=$(echo $generated | jq '. | { changed_at: .changed_at, from_revision: .from_revision, to_revision: .to_revision, pull_requests: .pull_requests | map({title: .title}) }')
          filter_untagged=$(echo $filtered | jq '. | select(.to_revision != "")')
          filter_empty=$(echo $filter_untagged | jq '. | select(.pull_requests | length != 0)')
          filter_type=$(echo $filter_empty | jq 'del(. | .pull_requests[] | select(.title | test("(feat|fix)") | not))')
          marked_stg=$(echo $filter_type | jq '. |= .+ {"is_staging": true}')
          result=$(echo $marked_stg | jq -s .)
          echo $result > generate/latest_changelog.json

          # 前回のchangelogがprdに未反映ならば削除する
          cat changelog.json | jq '.[] | select(.is_staging | not)' | jq -s . > generate/current.json
          jq -s '.[0] + .[1]' generate/latest_changelog.json generate/current.json > generate/pre_changelog.json
          mv generate/pre_changelog.json changelog.json
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      # TODO: git user
      - name: Git commit
        run: |
          git config user.name $user_name
          git config user.email $user_email
          git add .
          git commit -m "chore: generate changelog"
          git push origin main
