name: Generate Change Log for staging

on:
  pull_request:
    types: [opened]
    branches:
      - "stg"
  workflow_dispatch:

env:
  user_name: ${{ vars.GIT_USER_NAME }}
  user_email: ${{ vars.GIT_USER_EMAIL }}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Tokyo"
      - name: Print Payload
        run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: Git tag
        run: |
          # 古いgit tagを削除
          scripts/changelog/delete-old-tag.sh

          # 最新コミットにバージョンタグを付与
          scripts/changelog/git-tag-latest-version.sh

          # 最新コミットにstg.latestタグを付与
          git tag stg.latest
          git push origin stg.latest
      - name: Generate
        id: generate
        uses: ./.github/actions/generate
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          branch: main
      - name: Post Generate file
        run: |
          # 最新のchangelogにstgの目印を付与する
          marked_stg=$(echo ${{ steps.generate.outputs.changelog }} | jq '.[0] |= .+ {"is_staging": true}')
          echo $marked_stg

          # Changelog生成のための一時ファイル(gitignore)
          mkdir generate
          echo $marked_stg > generate/latest_changelog.json

          scripts/changelog/post-generate-file.sh
      - name: Git commit
        run: |
          git config user.name $user_name
          git config user.email $user_email
          git add .
          git commit -m "chore: generate changelog for staging"
          git push origin main
