# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0
      - name: git log
        run: git log --oneline
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Get Package
        run: go install github.com/Songmu/ghch/cmd/ghch@latest
      - name: Generate Change Log
        run: ghch --all
